eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9090/eureka/
spring:
  application.name: order-service
  profiles:
    active: file
order-data-db:
  orders:
    -
      id: 1
      orderName: Laptop
      price: 100.00
    -
      id: 2
      orderName: PenDrive
      price: 9.00